apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  labels:
    app: my-k8s-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      project: kgb
  template:
    metadata:
      labels:
        project: kgb
    spec:
      containers:
        - name: kgb-web
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1 
kind: Service 
metadata:
  name: my-service-1-lb-single
  labels:
    env: test
    owner: cheaster
spec:
  selector:
    project: kgb # select pods with those labels
  ports: 
    - name: app-listener
      protocol: TCP
      port: 80 #on LoadBalancer
      targetPort: 80 #on pod
  type: LoadBalancer