apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-deployment
  labels:
    app: {{ .Release.Name}}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name}}-deployment
  template:
    metadata:
      labels:
        project: {{ .Release.Name}}-deployment
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name}}-deployment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sh", "-c", "echo 'Private pull OK'"]

   